#!/bin/bash
#SBATCH -t 1:00:00
#SBATCH -n 24
#SBATCH -p short

#Load Modules
module load eb
module load Miniconda2

#Loading VirtualEnv
source activate qiime1

#Setting TempDir
export TMPDIR=~/qiime_tmp

#Make OTU network for 16 17 18 core microbiome. L2 level.
echo "making OTU network all L2"
time make_otu_network.py -i ~/bioc3301/all_years/summarised_core_OTUs/core_table_50_L2.biom -m ~/bioc3301/merged_map_updated.tsv -o ~/bioc3301/all_years/cytoscape

Make OTU network for 16 17 18 core microbiome. L3 level.
echo "making OTU network all L3"
time make_otu_network.py -i ~/bioc3301/all_years/summarised_core_OTUs/core_table_50_L3.biom -m ~/bioc3301/merged_map_updated.tsv -o ~/bioc3301/all_years/cytoscape_L3

#deactive virtual environment
source deactivate
