#!/bin/bash
#SBATCH -t 1:00:00
#SBATCH -n 24
#SBATCH -p short

#Load Modules
module load eb
module load Miniconda2

#Loading VirtualEnv
source activate qiime1

#Setting TempDir
export TMPDIR=~/qiime_tmp

#make 2d PCOA Plot of 16 17 Core Microbiome 
echo "make 2d plot"
time make_2d_plots.py -i ~/bioc3301/16_17/1617_CDA/bdiv_even385956/unweighted_unifrac_pc.txt -m ~/bioc3301/merged_map_updated.tsv -b Year -o ~/bioc3301/16_17/1617_CDA/

#deactivate virtual environment
source deactivate
