#!/bin/bash
#SBATCH -t 0:30:00
#SBATCH -n 24
#SBATCH -p short

#Load Modules
module load eb
module load Miniconda2

#Loading VirtualEnv
source activate qiime1

#Setting TempDir
export TMPDIR=~/qiime_tmp

#Removing samples
echo "removing 2018 samples from corrected merged OTU table"
time filter_samples_from_otu_table.py -i ~/bioc3301/corrected_merged_otu_table.biom -o ~/bioc3301/16_17/1617_merged_otu_table.biom --sample_id_fp ~/bioc3301/16_17/ids.txt

#deactivating virtual environment
echo "deactivating virtual environment"
source deactivate
