#!/bin/bash
#SBATCH -t 0:30:00
#SBATCH -n 24
#SBATCH -p short

#Load python modules
module load eb
module load Miniconda2

#Activate Virtual Environment
echo "activating virtual environment"
source activate qiime1

#Set Temporary Directory
export TMPDIR=~/qiime_tmp

#Summarise 16 17 merged OTU table, 2018 samples removed
echo "summarising merged BIOM table"
biom summarize-table -i ~/bioc3301/16_17/1617_merged_otu_table.biom -o ~/bioc3301/16_17/1617_merged_otu_table_summary.txt

#deactivate virtual environment
source deactivate
