#!/bin/bash
#SBATCH -t 2:00:00
#SBATCH -n 24
#SBATCH -p normal

#Loading Python Modules
module load eb
module load Miniconda2

#Activating Virtual Environment
echo "Loading virtual environment"
source activate qiime1

#Setting Temporary Directory
export TMPDIR=~/qiime_tmp

#Picking OTUs
echo "picking closed ref OTUs with SILVA database"
time pick_closed_reference_otus.py -i ~/bioc3301/2018_02_smb/demultiplex_Q20/seqs.fna -o ~/bioc3301/2018_02_smb/SILVA_OTUs/ -r ~/SILVA_128_QIIME_release/rep_set/rep_set_16S_only/97/97_otus_16S.fasta -t ~/SILVA_128_QIIME_release/taxonomy/16S_only/97/majority_taxonomy_all_levels.txt -a -O 16

#Deactivating Virtual Environment
source deactivate
~
